// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gtOrGloxUKMdhnDEUWf8TMJFgmI16gE',
    appId: '1:326923139164:web:329c727c2af601d12e4e99',
    messagingSenderId: '326923139164',
    projectId: 'test-83a42',
    authDomain: 'test-83a42.firebaseapp.com',
    storageBucket: 'test-83a42.appspot.com',
    measurementId: 'G-JG7R32E806',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kNv0yUOr_h9sjiYH-AvIHp9GQL1WRxs',
    appId: '1:326923139164:android:7254849d49616b242e4e99',
    messagingSenderId: '326923139164',
    projectId: 'test-83a42',
    storageBucket: 'test-83a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5AJFjW7Gjo0ZUot7qApKKi_onaeW1Bc',
    appId: '1:326923139164:ios:91c2bc72e346d3212e4e99',
    messagingSenderId: '326923139164',
    projectId: 'test-83a42',
    storageBucket: 'test-83a42.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5AJFjW7Gjo0ZUot7qApKKi_onaeW1Bc',
    appId: '1:326923139164:ios:91c2bc72e346d3212e4e99',
    messagingSenderId: '326923139164',
    projectId: 'test-83a42',
    storageBucket: 'test-83a42.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gtOrGloxUKMdhnDEUWf8TMJFgmI16gE',
    appId: '1:326923139164:web:b7e738e2b434d9a92e4e99',
    messagingSenderId: '326923139164',
    projectId: 'test-83a42',
    authDomain: 'test-83a42.firebaseapp.com',
    storageBucket: 'test-83a42.appspot.com',
    measurementId: 'G-SGVGXHPW7Q',
  );
}
